### ISSUE TITLE
Default Base and Relative Paths

### ISSUE THREAD

**Issue by Crisfole** [kwhitley/itty-fetcher#2] opened 2022-09-12 04:07 UTC
The default behavior here in-browser (`base: ''`) results in a base url relative to your current pathname (on this page, relative to `/kwhitley/itty-fetcher/issues/new`). This has real fun results when you simply concatenate other stuff (`whatever/test`) for instance.

In that case I'd be fetching against `/kwhitley/itty-fetcher/issues/whatever/test` (note the missing `new` path segment). This gets more confusing since if your route *happens* to end in a slash (`.../new/`, which is allowed and navigable on github) then it does *not* strip the `new` (since it's relative to the `/`). Even worse, if you have a `<base>` tag with a value set: `<base href="http://example.com" target="_blank">` it will be relative to the href there, which might be completely different (in this case `http://example.com/whatever/test`).

All that can be better controlled with the second parameter to URL: `new URL('whatever/test', 'http://www.github.com/kwhitley/itty-fetcher/')`.  I see a few options for solving this:

1. Test and warn (`if (!base.endsWith('/')) console.warn("Your base does not end in `/` and so ...");`)
2. A template literal type for base: ````base: `${string}/````
3. Using the URL constructor to combine the base and path (downside: the vase will need to be a full URL (including protocol [http/https]) so you may have to do more munging than you want. This allows for easy query param tweaking if you want your base to include share query params (like an Authoriation, for example).

Sorry for the wall of text, feel free to close. Just stuff I've been stewing on since our twitter discussion.

**Comment by kwhitley** [comment] 2022-09-12 15:05
This is great stuff!

Couple things:
1. In the first example, appending `whatever/test` to `/kwhitley/itty-fetcher/issues/new` should produce the malformed `/kwhitley/itty-fetcher/issues/newwhatever/test`, not omit the "new" bit.  I've run into this scenario myself.
2. To keep the lib down in size (and in keeping with the "itty" series), we'll need to find both the easiest/intuitive solution to this (as well as query string handling) as well as the smallest one.  Things like helpful error messaging just probably won't be in scope (as one of the costliest solutions space-wise).  But perhaps a lightweight regex replace inline might do the trick, or an internal URL constructor.

Gonna start playing around with these ideas, and would certainly welcome any continued input from your end!

**Comment by kwhitley** [comment] 2022-09-12 15:08
Regarding relative paths, intelligently transposing relative `../something` onto another path is likely out of scope here as well, due to the space constraints of dealing with edge cases like that.  If we can come up with a super light regex pass to merge those appropriately, it may be worth inclusion, but otherwise it'll be one of those situations where "you can totally give it bad URLs, so... just be careful not to do that".

Guard rails aren't included in these micro-libraries to help keep them micro! :)

**Comment by Crisfole** [comment] 2022-09-12 17:10
Yeah for sure! The intelligent relative pathing is granted free if you use the `URL` constructor with a base ending in `/`:

```ts
new URL("test/123", new URL("http://example.com/api/v1/")).toString()
'http://example.com/api/v1/test/123'
new URL("test/123", new URL("http://example.com/api/v1")).toString()
'http://example.com/api/test/123'
new URL("/test/123", new URL("http://example.com/api/v1/")).toString()
'http://example.com/test/123'
new URL("/test/123", new URL("http://example.com/api/v1")).toString()
'http://example.com/test/123'
```

In my mind the most intuitive of these is the first where you'd store `base` as:

```ts
base = new URL(base.replace(/([^/])$/, '$1/'));
```

and you'd always strip a leading `/` on fetch:

```ts
fetch(new URL(path.replace(/^\//, ''), base), { /* existing */ });
```

**Comment by Crisfole** [comment] 2022-09-12 17:10
By using the URL constructor you can also easily tweak the query params by using `url.searchParams.append(...)`

**Comment by kwhitley** [comment] 2022-09-12 18:03
So... this actually brings up some concerns. So if we were to use the URL constructor, the base is technically a base for relative pathing, but can be completely ignored/overridden by downstream calls, as you've demonstrated:
```js
fetcher({ base: 'https://foo.bar.baz/api/v1/' }).get('test/123')
// expected --> https://foo.bar.baz/api/v1/test/123
// actual   --> https://foo.bar.baz/api/v1/test/123

fetcher({ base: 'https://foo.bar.baz/api/v1' }).get('/test/123')
// expected --> https://foo.bar.baz/api/v1/test/123
// actual   --> https://foo.bar.baz/test/123

fetcher({ base: 'https://foo.bar.baz/api/v1/' }).get('/test/123')
// expected --> https://foo.bar.baz/api/v1/test/123
// actual   --> https://foo.bar.baz/test/123

fetcher({ base: 'https://foo.bar.baz/api/v1/' }).get('../test/123')
// expected --> https://foo.bar.baz/api/v1/test/123 or shouldn't be allowed
// actual   --> https://foo.bar.baz/api/test/123
```

Basically if you set a base, I would expect that to set the absolute base path, not a relative one... as in, downstream requests shouldn't be able to swim upstream of that base.  At least in my mind... 

Also, while I should certainly check for/eliminate double slashes, I don't know for sure if it's safe to auto-append one to a base... as not all APIs play nicely with trailing slashes.

**Comment by kwhitley** [comment] 2022-09-12 18:07
> Also, while I should certainly check for/eliminate double slashes, I don't know for sure if it's safe to auto-append one to a base... as not all APIs play nicely with trailing slashes.

Now, perhaps if you've given both a base and a segment (I'd like to support an undefined, like: `fetcher({ base: 'somewhere' }).get()`, perhaps it would be safe to strip a leading slash/dots from the segment URL to prevent upstream swimming, and *add* a trailing slash to the base to properly join them using the URL constructor...

**Comment by Crisfole** [comment] 2022-09-13 15:10
I totally agree, and have absolutely no clear solution to the problem. I do know that even _with_ this knowledge in mind I regularly screw this up. Maybe renaming from 'base' which has a defined meaning in HTML land could work? "root", maybe?

**Comment by Crisfole** [comment] 2022-09-14 12:37
@kwhitley, I just re-read your comment and I'm pretty sure your comment is precisely what I intended (given both base and segment, strip the leading from the segment, add the trailing to the base). In the case where base or segment is missing my comments are irrelevant anyway.

**Comment by kwhitley** [comment] 2022-09-30 17:14
So... I'm still completely torn on this.  I **really** believe a base path (and I use the word base/root interchangeably, sorry!) should not allow upstream swimming.  A simple/naive concat honors that, while also being about the floor in terms of characters/bytes.  If this handles the 90-95% crowd, then it should be the base - if not, then we should consider switching.  

In these "itty" microlibs, I'd always prefer the minority add (and be able to add) the extra functionality, rather than it going along for the ride into the bulk of users that'll never gain from the extra functionality.

So with that in mind, I'd like us to:

1. Come up with some *likely* (not extreme edge case) use-cases where we'd actually want/need to keep it truly relative?  I'm personally struggling to think of any... all my API routing/fetching is additive, where a naive concat works fine.
2. Consider exposing the concat method as an option to override?  This would allow folks to switch methods out as-needed...

**Comment by kwhitley** [comment] 2022-09-30 17:14
@danawoodman tagging you in as well!

**Comment by danawoodman** [comment] 2022-09-30 17:49
My two cents:

- If I do `fetcher().get("/foo")` I expect it to fetch literal `/foo`
- If I do `fetcher({ base: "https://example.com" }).get("/foo")` I expect it to fetch `https://example.com/foo`
- I don't personally think I'd ever do `fetcher({ base: "https//example.com/api/v1" }).get("../../foo")`, I would just use a new fetcher instance or something
- I don't think setting a trailing slash on your `base` makes sense since `.get("foo")` feels awkward and imprecise. I say follow standards like how Express does things (eg `get("/foo")`). 
- I think using `URL` to construct the actual URL makes sense as it is designed for this, even if it adds a few extra bytes.

**Comment by kwhitley** [comment] 2022-09-30 18:02
> My two cents:
> 
> * If I do `fetcher().get("/foo")` I expect it to fetch literal `/foo`

+1

> * If I do `fetcher({ base: "https://example.com" }).get("/foo")` I expect it to fetch `https://example.com/foo`

+1

> * I don't personally think I'd ever do `fetcher({ base: "https//example.com/api/v1" }).get("../../foo")`, I would just use a new fetcher instance or something

Yeah I can't either, especially given how easy/cheap it is to re-instantiate.

> * I don't think setting a trailing slash on your `base` makes sense since `.get("foo")` feels awkward and imprecise. I say follow standards like how Express does things (eg `get("/foo")`).

Agree.  However, does it hurt us any to support both?  If I recall, what I did was 

> * I think using `URL` to construct the actual URL makes sense as it is designed for this, even if it adds a few extra bytes.

Are there any advantages to this, if as @Crisfole suggests above, we strip leading slashes from the fetch (non-base) for appending?  The only case I could see would be for allowing relative/upstream fetches (using leading `../`)...  if that's the only use-case, and we decide that's not a common pattern, then perhaps its not worth the extra bytes?

Regardless I think we can merge your PR (using existing logic) and refine once merged.  We should also create a series of tests to explicitly define the expected behavior in these concat situations (if nothing else, so we don't break it going forward after we've decided on a pattern)!

**Comment by danawoodman** [comment] 2022-09-30 20:25
> Agree. However, does it hurt us any to support both? If I recall, what I did was

Don't think its an issue to support either/or


> Are there any advantages to this, if as @Crisfole suggests above, we strip leading slashes from the fetch (non-base) for appending? The only case I could see would be for allowing relative/upstream fetches (using leading `../`)... if that's the only use-case, and we decide that's not a common pattern, then perhaps its not worth the extra bytes?
> 
> Regardless I think we can merge your PR (using existing logic) and refine once merged. We should also create a series of tests to explicitly define the expected behavior in these concat situations (if nothing else, so we don't break it going forward after we've decided on a pattern)!

I don't think anything has to be done at this point if we're ok with the default behavior, which I'm ok with. 

For example, in SK, we would leave `basePath` off and just to `fetcher().get('/api/foo/bar')` on the client and it would do what we expect since SK modifies the built in fetch (well, i BELIEVE this should work, haven't verified).

For service side stuff, you can't use relative so it makes sense to use a base path or a full URL in your query.

I'm happy with how it is now from my light usage so far.

**Comment by Crisfole** [comment] 2022-09-30 23:06
I believe we landed at "don't" for weird base crap.

**Closed as completed** 2022-09-30 23:24 UTC
